#lang slideshow
(slide (para #:align 'center "The Joy(?) of embedding with mruby"))
(slide (para #:align 'center "name? matz? eMbedded?"))
(slide (para #:align 'center "alternative ruby interpreter(ISO!)"))
(slide (para #:align 'center "mgems, not rubygems. separate build system. bytecode compiler!"))
(slide (para #:align 'center "What is the meaning of embedded? To put it inside of something else"))
(slide (para #:align 'center "VST plugin! irb on the web! web servers! mindstorms! microcontrollers!"))
(slide (para #:align 'center "down to 100K disk(rom), 40K ram. fingernail. This is still too big for most MCUs!"))
(slide (para #:align 'center "You might be expecting a project and workflow report, and this is not what the talk is about"))
(slide (para #:align 'center "it takes effort to take something big and make it small"))
(slide (para #:align 'center "when you get down to the metal, raw edges abound"))
(slide (para #:align 'center "C interface, bytecode"))
(slide (para #:align 'center "operating systems, cross-compiling and build systems(trusterd, ngx-ruby)"))
(slide (para #:align 'center "why? why not?"))
(slide (para #:align 'center "ruby for me has always been a runtime, not just a way to run rails"))
(slide (para #:align 'center "this is still how it's done in Japan! remember that ISO number?"))
(slide (para #:align 'center "why bytecode? why lua?"))
(slide (para #:align 'center "so start exploring with a familiar door that will lead to a maze of twisty passageways, all alike"))

(slide (para #:align 'center "links: wheelchair, real-time audio, web-irb"))
(slide (para #:align 'center "@mechazoidal , http://kurokoproject.com"))
